all:
 children:
   downloader:
              hosts:
                radarr0.dial4tech.com:
                sonarr0.dial4tech.com:
                jackett0.dial4tech.com:
   bittorrent:
               hosts:     
                 deluge0.dial4tech.com:
                 qbittorrento.dial4tech.com:
   streamer:
             hosts:
               plex0.dial4tech.com:
               jellyfin.dial4tech.com:
   managment:
            hosts:
              tautuli.dial4tech.com:
              ombi.dial4tech.com:
