---
- hosts: all

  become: true
  tasks:
    - name: Apt update cache
      apt:
        update_cache: true

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes     