---
 - name: Install GitHub
   hosts: all
   become: true
   tasks:
    - name: Add GPG key
      apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        state: present
    - name: Add docker repository to apt
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        become: true
    - name: Install GitHub
      apt:
        name: gh
        state: present
      become: true