---
 - name: Install GitHub
   hosts: all
   become: true
   tasks:
    - name: Gh Key Ring
      ansible.builtin.shell:
        cmd: type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y) curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \ && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \ && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        
 - name: Upgrade packages
   apt:
     upgrade: yes
     autoremove: yes
     autoclean: yes
   become: true

 - name: Install GitHub
   apt:
     name: gh
     state: present
   become: true