---
- name: OvrSrrTwingate
  hosts: Cloud
  become: true
  tasks:
    - name: Twingate Auth
      ansible.builtin.shell:
        cmd: twingate auth sonarr ; twingate auth radarr ; twingate auth Tautulli


