---
- name: Install Traffic
  hosts: Cloud
  become: true
  tasks:
    - name:  Create volume
      ansible.builtin.shell:
        cmd: docker volume create traffic_data
      
    - name: Install Traffic  
      ansible.builtin.shell:
        cmd: docker run -d